name: Java CI with Gradle

on:
  push:
    branches: [ updtest ]
  pull_request:
    branches: [ updtest ]

jobs:
  build:
    strategy:
      matrix:
        # Use these Java versions
        java: [
          1.8,   # Optifabic current uses
          16,    # Minimum supported by Minecraft
          17,    # Current Java LTS
        ]
        # and run on both Linux and Windows
        os: [ubuntu-latest, windows-2022]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: Grant execute permission for gradlew
        if: ${{ runner.os != 'Windows' }}
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build --stacktrace --info
      - name: Upload a Build Artifact
        if: ${{ runner.os == 'Linux' && matrix.java == '17' }} # Only upload artifacts built from latest java on one OS
        uses: actions/upload-artifact@v2.1.4
        with:
          name: Optifabric-Artifact
          path: build/libs/optifabric-*.*.jar
          if-no-files-found: error
